### ISSUE TITLE
Create shiny app documentation files

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/Visium_SPG_AD#51]
Similar to https://github.com/LieberInstitute/spatialDLPFC/issues/75. You could ask Abby for a DSgs if you need some help Sang Ho.

**Comment by shkwon17** [comment]
- this is the overview google doc: https://docs.google.com/document/d/11uuWmjq1JnqXr-x0hskk_9GDyOGfg0NDrkNFjX054kY/edit

- this is the spot/layer-level google doc: https://docs.google.com/document/d/1r9vSgAVG99sSPc8fGB8vsBoUVo_8_dG6eOduw8ZGtCw/edit#

- images
![spatialLIBD_static_cluster_path_groups_V10A27106_D1_Br3880_2022-09-27_21_41_38](https://user-images.githubusercontent.com/62270695/227519612-1d1c93de-5bfd-40d6-9fd4-4cc0c34a58a8.png)
![VIFAD_Fig1_300dpi (1)](https://user-images.githubusercontent.com/62270695/227519647-15a7d38e-9f3f-4086-9664-6a0fcd5c4388.png)

**Comment by shkwon17** [comment]
The URL of the webpage that contains the video: https://www.10xgenomics.com/products/spatial-proteogenomics. 

The video itself doesn't have a direct URL.

<img width="758" alt="image" src="https://user-images.githubusercontent.com/62270695/227571692-9fe5fe8c-7917-4608-8d3b-20fcad54d731.png">

**Comment by shkwon17** [comment]
- [ ] https://github.com/LieberInstitute/Visium_SPG_AD/issues/79

**Comment by shkwon17** [comment]
- [ ] Add in the introduction to Samui to the google doc (Sang Ho)
