### ISSUE TITLE
Grubman et al 2019

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/Visium_SPG_AD#69]
* Number of sets: 6 cell types * concordance (2 options) = 12 sets + direction 6 sets = 18 sets
* Note: snRNA-seq

* Direction available: `Grubman.LogFC (AD vs Control a priori)`. There's not that many genes.
* Statistics available: No. But we have `Concordance`. 

- [ ] For each cell type, use all genes (ignore `Concordance`)
- [ ] For each cell type, filter to `Concordance == TRUE`
- [ ] For each cell type, use all genes (ignore `Concordance`), and separate by direction.

Some might be too small also.

**Comment by shkwon17** [comment]
Yes, it was the single gene, but we agreed we could make the interpretation/implication about microglia and their potential significance given this result!
