### ISSUE TITLE
GO-BP and KEGG analyses

### ISSUE THREAD

**Issue by shkwon17** [LieberInstitute/Visium_SPG_AD#73]
-Performing 
1) GO-BP (Biological Process) or -MF (Molecular function)
2) KEGG 

**-Sang Ho's expected results
1) picking up anything relevant to complement system and/or inflammatory responses
2) picking up anything relevant to ubiquitin/proteasome system
3) picking up anything relevant to neurodegenerative diseases such as Alzheimer's, Parkinson's, Huntington's and others.**

-FDR threshold for both DE gene selection and analyses can be discussed, but FDR<0.1 is very likely. 

-Sang Ho's suggested directions last time
1) merging enriched genes from the Ab and n_Ab dataset at FDR <0.1 (or FDR < 0.2)
 e.g., 50 enriched genes from Ab + 146 enriched genes from n_Ab = 196 genes at FDR<0.2

2) merging depleted genes from  the Ab and n_Ab dataset at FDR <0.1 
e.g., 687 depleted genes from Ab + 2329 depleted genes from n_Ab =  3016 genes at FDR<0.1  

Update on 03232023: 

- Utilized Metascape: https://metascape.org/gp/index.html#/main/step1 (https://www.nature.com/articles/s41467-019-09234-6) 
- Ran GO and KEGG for 1) 196 enriched DEGs of Ab+n_Ab at FDR<0.2 and 2) 3016 depleted DEGs of Ab+n_Ab at FDR<0.1 
- p-value threshold was set to p-value < 0.05 for the analyses
- 8443 genes were used as a background geneses
- whether I can use this data just to implicate their general biological processes (no interpretation about enrichment/depletion of the biological processes)
![HeatmapSelectedGO](https://user-images.githubusercontent.com/62270695/227396632-682df793-1441-4095-b459-a68f6c93cc8a.png)
![HeatmapSelectedGOKEGG](https://user-images.githubusercontent.com/62270695/227396667-87e598b0-59b6-4b1b-a4d7-ed0c9c5fa31d.png)
![HeatmapSelectedGO](https://user-images.githubusercontent.com/62270695/227396700-4af25cfc-013d-4fdf-928f-de00b242a09e.png)
![HeatmapSelectedGO](https://user-images.githubusercontent.com/62270695/227396726-d8d05c35-ba6b-4c0e-bc94-5ade57afbf0d.png)

**Comment by shkwon17** [comment]
**Update on 03-31-2023 after a coding session:**

- [ ]  Instead of manually combining and editing gene sets as Sang Ho did previously, Leo will pseudobuck and run DE testing again to select for genes that are 1) enriched and 2) depleted in the Abeta-associated microenvironment (Abeta + Next Abeta), which is the formal way to identify DE genes associated with the Abeta-associated microenvironment. Sang Ho created the acronym 'AAME' to denote the Abeta-associated microenvironment. However, anyone can change this acronym for clarity.

- [ ] We plan run 1) GO-BP (GO-MF, only if necessary) and 2) KEGG analyses with the two gene sets for 1) enriched and depleted genes.

    - Currently considered thresholds to try out (which can be flexible):
              - FDR threshold for gene selection (i.e., FDR of each gene): 0.1, but Sang Ho wonders if we can relax it to 0.2, if possible/needed. 
              - P-value threshold for GO and KEGG analyses: 0.05, but if the threshold needs to be more conservative, then 0.01
              - FDR threshold for GO and KEGG analyses (if needed): 0.1, but Sang Ho wonders if we can relax it to 0.2, if possible/needed. 
    - **Sang Ho's expected results**:
1. picking up anything relevant to complement system and/or inflammatory responses
2. picking up anything relevant to ubiquitin/proteasome system
3. picking up anything relevant to neurodegenerative diseases such as Alzheimer's, Parkinson's, Huntington's and others.**
            
Just a diagram to illustrate the analysis approach:
![Untitled (24)](https://user-images.githubusercontent.com/62270695/229194674-86ef99c7-95fe-4e31-a80b-44ac5c18a3ed.png)

**Comment by lcolladotor** [comment]
Analyses are done =)
