### ISSUE TITLE
Twitter thread describing the pre-print

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/Visium_SPG_AD#81]
Let's work on this @shkwon17 too ^^.

I'll need to update https://github.com/LieberInstitute/spatialLIBD/blob/7b2a9891428967744ab4adf152188d4b591903da/vignettes/spatialLIBD.Rmd#L594 once this Twitter thread is out.

We'll use the same strategy as in `spatialDLPFC` where we'll ask all co-authors to quote-tweet your first tweet, and your first tweet should include the link to the pre-print for AltMetric to recognize it. See my CV for links to Twitter threads for nearly all my papers so you can get an idea on how to make such a thread. See also https://posit.co/resources/videos/phrasing-communicating-data-science-through-tweets-gifs-and-classic-misdirection/.

**Comment by shkwon17** [comment]
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/62270695/231960664-0073ce75-c64f-493d-bf15-764a27c5a161.png">
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/62270695/231960720-e1e239bb-686a-4f79-95be-760b513afb44.png">
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/62270695/231960772-72783a6c-59df-4d8b-a909-131f48a30cda.png">
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/62270695/231960822-26386641-05aa-4f34-bc50-da02e42dd57b.png">
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/62270695/231961001-0a17efa4-6964-4f31-b4ce-ee93a1a6b9c8.png">
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/62270695/231961085-d22bb783-93cc-488e-8c5a-a292103a272e.png">
