### ISSUE TITLE
Spot deconvolution using Mathys et al as the reference

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/Visium_SPG_AD#82]
Hi Nick,

Can you help me run `cell2location` on this dataset using as input reference the Mathys et al snRNA-seq data?

Thanks!

Details:

* Mathys et al paper: https://doi.org/10.1038/s41586-019-1195-2
* Mathys et al code for reading the data: https://github.com/LieberInstitute/HumanPilot/blob/eca2070bcd09282a8adbdc3de310084834b7cd9e/Analysis/Layer_Guesses/ad_snRNAseq_recast.R#L13-L25
* Mathys et al location at JHPCE: `/dcs04/lieber/lcolladotor/with10x_LIBD001/HumanPilot/Analysis/Layer_Guesses/mathys/`. Note that `/dcs04/lieber/lcolladotor/with10x_LIBD001/HumanPilot/Analysis/Layer_Guesses/rda` contains some pseudobulked objects from the Mathys et al data, though I believe that you need the full raw data (prior to pseudobulking) for identifying marker genes with `DeconvoBuddies`.

```
$ ls -lh /dcs04/lieber/lcolladotor/with10x_LIBD001/HumanPilot/Analysis/Layer_Guesses/mathys/
total 680M
-rw-rw---- 1 lcollado lieber_lcolladotor 5.0M Feb 20  2020 filtered_column_metadata.txt
-rw-rw---- 1 lcollado lieber_lcolladotor 1.5G Feb 20  2020 filtered_count_matrix.mtx
-rw-rw---- 1 lcollado lieber_lcolladotor 116K Feb 20  2020 filtered_gene_row_names.txt
-rw-rw---- 1 lcollado lieber_lcolladotor 1.9M Feb 20  2020 mathys_data.zip
-rw-rw---- 1 lcollado lieber_lcolladotor 6.9K Feb 20  2020 mathys_meta.zip
-rw-rw---- 1 lcollado lieber_lcolladotor 325K Feb 20  2020 ROSMAP_Clinical_2019-05_v3.csv
-rw-rw---- 1 lcollado lieber_lcolladotor  68K Feb 20  2020 snRNAseqPFC_BA10_assay_scRNAseq_metadata.csv
-rw-rw---- 1 lcollado lieber_lcolladotor 4.5K Feb 20  2020 snRNAseqPFC_BA10_biospecimen_metadata.csv
-rw-rw---- 1 lcollado lieber_lcolladotor  28K Feb 20  2020 snRNAseqPFC_BA10_id_mapping.csv
-rw-rw---- 1 lcollado lieber_lcolladotor  580 Feb 20  2020 snRNAseqPFC_BA10_Sample_key.csv

$ ls -lh /dcs04/lieber/lcolladotor/with10x_LIBD001/HumanPilot/Analysis/Layer_Guesses/rda/mathys*
-rw-r----- 1 ajaffe   lieber_lcolladotor  11M May 11 15:20 /dcs04/lieber/lcolladotor/with10x_LIBD001/HumanPilot/Analysis/Layer_Guesses/rda/mathys_pseudobulked_broad.Rdata
-rw-rw---- 1 lcollado lieber_lcolladotor 134K Feb 21  2020 /dcs04/lieber/lcolladotor/with10x_LIBD001/HumanPilot/Analysis/Layer_Guesses/rda/mathys_pseudobulked_dupCor.Rdata
-rw-rw---- 1 lcollado lieber_lcolladotor 134K Feb 21  2020 /dcs04/lieber/lcolladotor/with10x_LIBD001/HumanPilot/Analysis/Layer_Guesses/rda/mathys_pseudobulked_layered_dupCor.Rdata
-rw-rw---- 1 lcollado lieber_lcolladotor  22M Feb 21  2020 /dcs04/lieber/lcolladotor/with10x_LIBD001/HumanPilot/Analysis/Layer_Guesses/rda/mathys_pseudobulked_layered.Rdata
-rw-rw---- 1 lcollado lieber_lcolladotor  53M Feb 21  2020 /dcs04/lieber/lcolladotor/with10x_LIBD001/HumanPilot/Analysis/Layer_Guesses/rda/mathys_pseudobulked_layered_specific_Ts.Rdata
-rw-rw---- 1 lcollado lieber_lcolladotor  46M Feb 20  2020 /dcs04/lieber/lcolladotor/with10x_LIBD001/HumanPilot/Analysis/Layer_Guesses/rda/mathys_pseudobulked.Rdata
-rw-rw---- 1 lcollado lieber_lcolladotor 195M Feb 21  2020 /dcs04/lieber/lcolladotor/with10x_LIBD001/HumanPilot/Analysis/Layer_Guesses/rda/mathys_pseudobulked_specific_Ts.Rdata
```

* Cell counts: use the `NDAPI` column we have on the SPE object for `wholegenome`. We won't run spot deconvolution on `targeted`.

Here's a bit a of a guide in terms of steps, though you are more familiar with the details than me:

- [x] Read in data: get familiar with cell types available. We will have to choose what is the appropriate resolution. 
- [x] Identify marker genes with the mean ratio strategy
- [x] Make violin plots + hockey stick plots to choose the right number of mean ratio marker genes per cell type
- [x] Run `cell2location` with `NDAPI` providing the information for the number of cells per spot
- [x] Make it easy to read in the results using `spatialLIBD::cluster_import()` or provide a script for doing so (I forget exactly how you did this for `spatialDLPFC`)

**Comment by Nick-Eagles** [comment]
`cell2location` results can be added to the `SpatialExperiment` with `cluster_import` as seen [here](https://github.com/LieberInstitute/Visium_SPG_AD/blob/f168b7036bbf0cdca7a3837db2d8f393509eca86/code/21_spot_deconvo/05_explore_results.R#L49-L51)
