### ISSUE TITLE
Use full gene set in Samui apps

### ISSUE THREAD

**Issue by Nick-Eagles** [LieberInstitute/Visium_SPG_AD#84]
Originally, due to a misunderstanding about Samui's capabilities and using its API, I [subsetted gene expression data](https://github.com/LieberInstitute/Visium_SPG_AD/blob/dbecaafa034df45939f456f52772dd700e8f7360/code/16_samui/01-SPG_images.py#L131-L133), which resulted in dropping some biologically interesting genes. The apps should be rebuilt and redeployed on AWS with the full gene set, using `add_chunked_feature` instead of `add_csv_feature` [here](https://github.com/LieberInstitute/Visium_SPG_AD/blob/dbecaafa034df45939f456f52772dd700e8f7360/code/16_samui/01-SPG_images.py#L170).

**Comment by lcolladotor** [comment]
Is this still an active issue?

**Comment by Nick-Eagles** [comment]
I believe so. I haven't addressed it, but I'll check back with Sang Ho to make sure he's still interested in this being changed.

**Comment by lcolladotor** [comment]
Ping about this
