### ISSUE TITLE
difference between raw-data/10x_files/Lieber_Transfer and Lieber_Transfer_10x_Alignments

### ISSUE THREAD

**Issue by JiawenChenn** [LieberInstitute/Visium_SPG_AD#85]
Hi,

Thanks for organizing the repository. I am trying to use the 10x format data. I found two folders in the raw-data folder but not sure which to use. Could you inform me which is the right one to use? Thanks!

Best,
Jiawen

**Comment by lcolladotor** [comment]
Hi,

`Lieber_Transfer` files are the ones we ended up using. See https://github.com/LieberInstitute/Visium_SPG_AD/blob/6ef1a1225d3dcd115f6272711ab684d050711378/code/01_bamtofastq/spaceranger_our_alignments_nocr11.sh#L35 and https://github.com/LieberInstitute/Visium_SPG_AD/blob/6ef1a1225d3dcd115f6272711ab684d050711378/code/02_spaceranger/spaceranger.sh#L56.

At some point we were debugging some issue with 10x and they sent us their `spaceranger` alignment files.

Best,
Leo
